import time
import network
from machine import Pin
from umqtt.robust import MQTTClient

import temperature_upb2 as pb   # generated by uprotobuf plugin

# -----------------------------------------------------
# GLOBAL CONFIG (REQUIRED BY MARKING SCHEME)
# -----------------------------------------------------

BROKER_IP  = "172.20.10.2"   # Raspberry Pi IP (MQTT broker)
TOPIC      = b"temp/pico"    # MQTT topic

OUTPUT_PIN = None            # e.g. "LED" on subscriber, None on publisher
PUB_IDENT  = "pico1"         # e.g. "pico1" on publisher, None on subscriber

#   TO RUN AS PUBLISHER (temp sensor):
#       BROKER_IP  = "..." (Pi IP, not None)
#       TOPIC      = b"..."
#       PUB_IDENT  = "pico1" (non-None)
#       OUTPUT_PIN = None
#
#   TO RUN AS SUBSCRIBER (LED average):
#       BROKER_IP  = "..." (Pi IP, not None)
#       TOPIC      = b"..."
#       PUB_IDENT  = None
#       OUTPUT_PIN = "LED"   (or a GPIO number like 15)
#
# -----------------------------------------------------
# CONFIG VALIDATION / MODE DECISION
# -----------------------------------------------------

def is_publisher():
    return (BROKER_IP is not None and TOPIC is not None and
            PUB_IDENT is not None and OUTPUT_PIN is None)

def is_subscriber():
    return (BROKER_IP is not None and TOPIC is not None and
            PUB_IDENT is None and OUTPUT_PIN is not None)

def validate_config():
    if BROKER_IP is None or TOPIC is None:
        print("Config error: BROKER_IP and TOPIC must be set")
        return False

    if is_publisher() or is_subscriber():
        return True

    # Any other combination should fail gracefully
    print("Config error: set either PUB_IDENT (publisher) OR OUTPUT_PIN (subscriber), but not both")
    return False

# -----------------------------------------------------
# WIFI CONNECT
# -----------------------------------------------------

def connect_wifi():
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    wlan.connect("Moes iPhone", "moe2drizzy")

    print("Connecting to WiFi...")
    for _ in range(20):
        if wlan.isconnected():
            print("Connected to WiFi")
            print("IP:", wlan.ifconfig()[0])
            return
        time.sleep(1)

    raise RuntimeError("WiFi failed to connect")

# -----------------------------------------------------
# COMMON HELPERS
# -----------------------------------------------------

def current_seconds():
    t = time.localtime()
    return t[3] * 3600 + t[4] * 60 + t[5]

# -----------------------------------------------------
# PUBLISHER LOGIC (TEMPERATURE SIDE)
# -----------------------------------------------------

def read_temp():
    # Replace with real sensor code if you have it
    # This just bounces between 24 and 30 degrees
    return 24 + (time.time() % 6)

def publish_loop():
    mqtt = MQTTClient(PUB_IDENT, BROKER_IP)
    mqtt.connect()
    print("Publisher connected as:", PUB_IDENT)

    while True:
        temp = read_temp()
        ts   = current_seconds()

        # Build protobuf message
        msg = pb.TemperaturemessageMessage()
        msg.id._value   = PUB_IDENT     # publisher ID
        msg.temp._value = temp          # temperature
        msg.time._value = ts            # time (seconds since midnight)

        # Serialise to bytes and publish
        data = msg.serialize()          # uprotobuf API: serialize()/parse()
        mqtt.publish(TOPIC, data)

        print("Published → {}: {:.2f}°C".format(PUB_IDENT, temp))
        time.sleep(2)

# -----------------------------------------------------
# SUBSCRIBER LOGIC (LED SIDE)
# -----------------------------------------------------

latest = {}      # { publisher_id : (temp, timestamp_seconds) }

def mqtt_callback(topic, msg_bytes):
    global latest

    try:
        m = pb.TemperaturemessageMessage()
        m.parse(msg_bytes)  # parse bytes into message

        pub_id = m.id._value
        temp   = m.temp._value
        # You could use m.time._value, but using receive time is simpler
        ts     = current_seconds()

        latest[pub_id] = (temp, ts)
        print("Received → {}: {:.2f}°C".format(pub_id, temp))

    except Exception as e:
        print("Error parsing protobuf:", e)

def run_subscriber():
    led = Pin(OUTPUT_PIN, Pin.OUT)
    mqtt = MQTTClient("subscriber", BROKER_IP)
    mqtt.set_callback(mqtt_callback)
    mqtt.connect()
    mqtt.subscribe(TOPIC)

    print("Subscriber listening on:", TOPIC)

    while True:
        mqtt.check_msg()   # process incoming messages

        now = current_seconds()
        temps = []

        # Keep only publishers from last 10 minutes (600 sec)
        for pid, (temp, ts) in list(latest.items()):
            if now - ts <= 600:
                temps.append(temp)
            else:
                # delete old entries to save memory
                del latest[pid]

        # Compute average temperature and drive LED
        if temps:
            avg = sum(temps) / len(temps)
            print("Average temperature:", avg)

            # LED on if avg > 25, else off
            led.value(1 if avg > 25 else 0)

        time.sleep(1)

# -----------------------------------------------------
# MAIN
# -----------------------------------------------------

def main():
    if not validate_config():
        return

    connect_wifi()

    if is_publisher():
        publish_loop()
    elif is_subscriber():
        run_subscriber()
    else:
        # Should never happen because of validate_config()
        print("Unknown mode – this should not happen.")

main()
